[build]
  base = ""
  command = "npm run build npx browserslist@latest --update-db"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
